# Generated by Django 3.2.12 on 2022-04-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_SMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='TodoTask',
        ),
    ]
